set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencnt][*]/D}] 2
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencntzerokeep]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencntzerokeep]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencntzerokeep]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencntzerokeep]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_msb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_msb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencntzerokeep]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencntzerokeep]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_msb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_msb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_msb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_msb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencntzerokeep]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencntzerokeep]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencntzerokeep]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencntzerokeep]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_msb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_msb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_msb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_msb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencntzerokeep]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencntzerokeep]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_msb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_msb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencntzerokeep]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencntzerokeep]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_msb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_msb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_msb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_msb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencntzerokeep]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencntzerokeep]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_msb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_msb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_msb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_msb][*]/D}] 1

set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][dosavexlsbraddr]/D}] 2
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xiphase]/D}] 2
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xiphase]/D}] 2
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xiphase]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xiphase]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnten]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnten]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntdone]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntdone]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][dosavexlsbraddr]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][dosavexlsbraddr]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xiphase]/D}] 2
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][dosavexlsbraddr]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][dosavexlsbraddr]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xiphase]/D}] 2
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][dosavexlsbraddr]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][dosavexlsbraddr]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xiphase]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xiphase]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnten]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnten]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntdone]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntdone]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][dosavexlsbraddr]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][dosavexlsbraddr]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xiphase]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xiphase]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnten]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnten]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntdone]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntdone]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nextxymsb]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][dosavexlsbraddr]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][dosavexlsbraddr]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[ctrl][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[ctrl][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xiphase]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xiphase]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcnten]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcnten]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcntdone]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcntdone]/D}] 1

set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/D}] 2
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencntzerokeep]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencntzerokeep]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_msb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_msb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_msb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_msb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][dosavexlsbraddr]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][dosavexlsbraddr]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xiphase]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xiphase]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnten]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnten]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcntdone]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcntdone]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencntzerokeep]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencntzerokeep]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_msb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_msb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_msb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_msb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nextxymsb]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nextxymsb]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][dosavexlsbraddr]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][dosavexlsbraddr]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[ctrl][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[ctrl][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xiphase]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xiphase]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcnten]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcnten]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcntdone]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcntdone]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencntzerokeep]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencntzerokeep]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_msb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_msb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_msb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_msb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][dosavexlsbraddr]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][dosavexlsbraddr]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xiphase]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xiphase]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnten]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnten]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcntdone]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcntdone]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencntzerokeep]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencntzerokeep]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_lsb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_lsb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcntzero]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcntzero]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_msb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_msb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_msb][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_msb][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nextxymsb]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nextxymsb]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][dosavexlsbraddr]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][dosavexlsbraddr]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[ctrl][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[ctrl][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][state][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][state][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xiphase]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xiphase]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcnt][*]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcnt][*]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcnten]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcnten]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcntdone]/D}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcntdone]/D}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicnt][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicnt][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencnt][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencnt][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicntzero]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicntzero]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencntzerokeep]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencntzerokeep]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_lsb][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_lsb][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_lsb][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_lsb][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcnt][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcnt][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntzero]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntzero]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_msb][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_msb][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_msb][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_msb][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][dosavexlsbraddr]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][dosavexlsbraddr]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xiphase]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xiphase]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnt][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnt][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnten]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnten]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcntdone]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcntdone]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicnt][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicnt][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencnt][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencnt][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicntzero]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicntzero]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencntzerokeep]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencntzerokeep]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_lsb][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_lsb][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_lsb][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_lsb][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcnt][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcnt][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcntzero]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcntzero]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_msb][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_msb][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_msb][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_msb][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nextxymsb]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nextxymsb]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][dosavexlsbraddr]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][dosavexlsbraddr]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[ctrl][state][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[ctrl][state][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][state][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][state][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xiphase]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xiphase]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcnt][*]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcnt][*]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcnten]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcnten]/CE}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcntdone]/CE}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcntdone]/CE}] 1

set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicnt][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicnt][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencnt][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencnt][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicntzero]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xicntzero]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencntzerokeep]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xishencntzerokeep]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_lsb][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_lsb][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_lsb][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_lsb][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcnt][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcnt][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntzero]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][slkcntzero]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_msb][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[iram][raddr_msb][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_msb][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[tram][raddr_msb][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nextxymsb]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][dosavexlsbraddr]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][dosavexlsbraddr]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[ctrl][state][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][state][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xiphase]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][xiphase]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnt][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnt][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnten]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcnten]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcntdone]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[0].mmmi/r_reg[prod][bigslkcntdone]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicnt][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicnt][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencnt][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencnt][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicntzero]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xicntzero]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencntzerokeep]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xishencntzerokeep]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_lsb][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_lsb][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_lsb][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_lsb][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcnt][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcnt][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcntzero]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][slkcntzero]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_msb][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[iram][raddr_msb][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_msb][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[tram][raddr_msb][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nextxymsb]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nextxymsb]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][dosavexlsbraddr]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][dosavexlsbraddr]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[ctrl][state][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[ctrl][state][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][state][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][state][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xiphase]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][xiphase]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcnt][*]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcnt][*]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcnten]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcnten]/R}] 1
set_multicycle_path -setup -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcntdone]/R}] 2
set_multicycle_path -hold -from [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][nbx][*]/C}] -to [get_pins {design_1_i/ecc_0/U0/mm[1].mmmi/r_reg[prod][bigslkcntdone]/R}] 1
